export const acupointEntries = {
  "LU 1": {
      "Acupoint": "LU 1",
      "Label": "LU 1",
      "Synonym": "Test data",
      "UMLS CUI": "",
      "Meridian": "LTest data",
      "Chinese Name": "Zhongfu",
      "English Name": "Central Treasury",
      "Location": " z zxczc.",
      "Reference": "Test data",
      "Indications": "Test data",
      "Acupuncture Method": "Test data",
      "Vasculature": "Test data",
      "Innervation": "Test data",
      "Curated": false,
      "onMRI": true
  },
  "LU 2": {
      "Acupoint": "LU 2",
      "Label": "LU 2",
      "Synonym": "Test data",
      "UMLS CUI": "",
      "Meridian": "LTest data",
      "Chinese Name": "Yunmen",
      "English Name": "Cloud Gate",
      "Location": " z zxczc.",
      "Reference": "Test data",
      "Indications": "Test data",
      "Acupuncture Method": "Test data",
      "Vasculature": "Test data",
      "Innervation": "Test data",
      "Curated": true,
      "onMRI": true
  },
  "ST 3": {
    "Acupoint": "ST 3",
    "Label": "ST 3",
    "Synonym": "Test data",
    "UMLS CUI": "",
    "Meridian": "STest data",
    "Chinese Name": "Cheng Qi",
    "English Name": "Not Available",
    "Location": " z zxcxadadadzc.",
    "Reference": "Test data",
    "Indications": "Test data",
    "Acupuncture Method": "Test data",
    "Vasculature": "Test data",
    "Innervation": "Test data",
    "Curated": true,
    "onMRI": false
  },
  "LR 4": {
    "Acupoint": "LR 4",
    "Label": "LR 4",
    "Synonym": "Test data",
    "UMLS CUI": "",
    "Meridian": "STest data",
    "Chinese Name": "Zhongfeng",
    "English Name": "Not Available",
    "Location": " z zxcxadadadzc.",
    "Reference": "Test data",
    "Indications": "Test data",
    "Acupuncture Method": "Test data",
    "Vasculature": "Test data",
    "Innervation": "Test data",
    "Curated": false,
    "onMRI": false
  }
}